frontend:
  url: http://127.0.0.1:3000
security:
  # secret-key: 
  allowed-hosts:
    - 127.0.0.1
    - localhost
    - ::1
  otp-expiration-hours: 24
  upload-files-max-mb: 500
database:
  name: rekono
  # user:
  # password:
  host: 127.0.0.1
  port: 5432
rq:
  host: 127.0.0.1
  port: 6379
email:
  host: 127.0.0.1
  port: 587
  # user:
  # password:
  tls: true
telegram:
  bot: Rekono
  # token: 
defect-dojo:
  url: http://127.0.0.1:8080
  # api-key:
  verify: false
  tags:
    - rekono
  product:
    auto-creation: true
  product-type: Rekono Project
  test-type: Rekono Findings Import
  test: Rekono Test
tools:
  cmseek:
    directory: /usr/share/cmseek
  log4j-scanner:
    directory: /opt/log4j-scanner
  gittools:
    directory: /opt/GitTools