version: '1.0'

services:
  postgres:
    restart: always
    image: postgres:14.2-alpine
    hostname: postgres
    container_name: postgres
    user: postgres
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      - internal
      - external
    environment:
      - POSTGRES_DB=rekono
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  redis:
    restart: always
    image: redis:7.0-rc-alpine
    hostname: redis
    container_name: redis
    user: redis
    expose:
      - 6379
    networks:
      - internal
  
  postfix:
    restart: always
    image: catatnight/postfix:latest
    hostname: postfix
    container_name: postfix
    expose:
      - 25
    networks:
      - internal
      - external
    environment:
      - maildomain=rekono.com
      - smtp_user=postfix:postfix

  initialize:
    restart: 'no'
    build:
      dockerfile: docker/rekono/Dockerfile
      target: backend
    command: sh -c "python manage.py migrate && python manage.py createsuperuser --no-input"
    container_name: initialize
    volumes:
      - ./config.yaml:/rekono/config.yaml:ro
    networks:
      - internal
    depends_on:
      - postgres
    environment:
      - RKN_DB_HOST=postgres
      - RKN_DB_USER=postgres
      - RKN_DB_PASSWORD=postgres
      - REKONO_HOME=/rekono
      - DJANGO_SUPERUSER_EMAIL=rekono@rekono.com
      - DJANGO_SUPERUSER_USERNAME=rekono
      - DJANGO_SUPERUSER_PASSWORD=rekono
  
  tasks-worker:
    restart: always
    build:
      dockerfile: docker/rekono/Dockerfile
      target: backend
    command: python manage.py rqworker tasks-queue
    hostname: tasks-worker
    volumes:
      - rekono:/rekono
      - ./config.yaml:/rekono/config.yaml:ro
    networks:
      - internal
    depends_on:
      - postgres
      - redis
    environment:
      - RKN_DB_HOST=postgres
      - RKN_DB_USER=postgres
      - RKN_DB_PASSWORD=postgres
      - RKN_RQ_HOST=redis
      - REKONO_HOME=/rekono
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

  executions-worker:
    restart: always
    build:
      dockerfile: docker/kali/Dockerfile
    command: python manage.py rqworker executions-queue
    hostname: executions-worker
    volumes:
      - rekono:/rekono
      - ./config.yaml:/rekono/config.yaml:ro
    networks:
      - internal
      - external
    cap_add:
      - NET_ADMIN
    depends_on:
      - postgres
      - redis
    environment:
      - RKN_DB_HOST=postgres
      - RKN_DB_USER=postgres
      - RKN_DB_PASSWORD=postgres
      - RKN_RQ_HOST=redis
      - REKONO_HOME=/rekono
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

  findings-worker:
    restart: always
    build:
      dockerfile: docker/rekono/Dockerfile
      target: backend
    command: python manage.py rqworker findings-queue
    hostname: findings-worker
    volumes:
      - rekono:/rekono
      - ./config.yaml:/rekono/config.yaml:ro
    networks:
      - internal
      - external
    depends_on:
      - postgres
      - redis
    environment:
      - RKN_DB_HOST=postgres
      - RKN_DB_USER=postgres
      - RKN_DB_PASSWORD=postgres
      - RKN_RQ_HOST=redis
      - RKN_TELEGRAM_TOKEN
      - REKONO_HOME=/rekono
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
    
  emails-worker:
    restart: always
    build:
      dockerfile: docker/rekono/Dockerfile
      target: backend
    command: python manage.py rqworker emails-queue
    hostname: emails-worker
    volumes:
      - rekono:/rekono
      - ./config.yaml:/rekono/config.yaml:ro
    networks:
      - internal
      - external
    depends_on:
      - redis
      - postfix
    environment:
      - RKN_DB_HOST=postgres
      - RKN_DB_USER=postgres
      - RKN_DB_PASSWORD=postgres
      - RKN_RQ_HOST=redis
      - RKN_EMAIL_HOST=${RKN_EMAIL_HOST:-postfix}
      - RKN_EMAIL_PORT=${RKN_EMAIL_PORT:-25}
      - RKN_EMAIL_USER=${RKN_EMAIL_USER:-postfix}
      - RKN_EMAIL_PASSWORD=${RKN_EMAIL_PASSWORD:-postfix}
      - REKONO_HOME=/rekono
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

  telegram-bot:
    restart: on-failure
    build:
      dockerfile: docker/rekono/Dockerfile
      target: backend
    command: python manage.py telegram_bot
    hostname: telegram_bot
    container_name: telegram-bot
    volumes:
      - rekono:/rekono
      - ./config.yaml:/rekono/config.yaml:ro
    networks:
      - internal
      - external
    depends_on:
      - postgres
      - redis
    environment:
      - RKN_DB_HOST=postgres
      - RKN_DB_USER=postgres
      - RKN_DB_PASSWORD=postgres
      - RKN_RQ_HOST=redis
      - RKN_TELEGRAM_TOKEN
      - REKONO_HOME=/rekono
  
  backend:
    restart: always
    build:
      dockerfile: docker/rekono/Dockerfile
      target: backend
    command: python manage.py runserver 0.0.0.0:8000
    hostname: backend
    container_name: backend
    expose:
      - 8000
    volumes:
      - rekono:/rekono
      - ./config.yaml:/rekono/config.yaml:ro
    networks:
      - internal
      - external
    depends_on:
      - postgres
      - redis
    environment:
      - RKN_DB_HOST=postgres
      - RKN_DB_USER=postgres
      - RKN_DB_PASSWORD=postgres
      - RKN_RQ_HOST=redis
      - RKN_ALLOWED_HOSTS=backend
      - RKN_DD_API_KEY
      - REKONO_HOME=/rekono
  
  frontend:
    restart: always
    build:
      dockerfile: docker/rekono/Dockerfile
      target: frontend
    command: serve -s dist
    hostname: frontend
    container_name: frontend
    expose:
      - 3000
    networks:
      - internal
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider

  nginx:
    restart: always
    build:
      dockerfile: docker/nginx/Dockerfile
    hostname: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/www/rekono/static:ro
    depends_on:
      - backend
      - frontend
    networks:
      - internal
      - external

volumes:
  postgres:
  rekono:

networks:
  internal:
    internal: true
  external:
