name: Check installation
on:
  workflow_dispatch:

env:
  RKN_USERNAME: rekono
  RKN_PASSWORD: rekono

jobs:
  docker:
    name: Test Docker environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Launch docker environment
        run: |
          docker-compose build
          docker-compose up -d

      - name: Test default credentials
        run: |
          sleep 2m
          curl -X POST --insecure -H 'Content-Type: application/json' https://127.0.0.1/api/token/ --data '{"username": "'"${RKN_USERNAME}"'", "password": "'"${RKN_PASSWORD}"'"}'
          RESPONSE=$(curl -X POST --insecure -H 'Content-Type: application/json' https://127.0.0.1/api/token/ --data '{"username": "'"${RKN_USERNAME}"'", "password": "'"${RKN_PASSWORD}"'"}' -o /dev/null -w '%{http_code}\n' -s)
          echo $RESPONSE
          if [ $RESPONSE != 200]; then exit 10; fi