name: Code style
on:
  workflow_dispatch:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      
      - name: Checkout
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
      
      - name: Flake8 check
        uses: valentijnscholten/flake8-your-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Install MyPy
        run: python3 -m pip install mypy==0.931
      
      - name: MyPy check
        run: mypy -v --namespace-packages --package rekono --install-types --no-interactive

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install ESLint
        run: |
          cd rekono/frontend/
          npm install .
          npm install -g eslint
      
      - name: ESLint check
        run: eslint rekono/frontend/ --ext .js,.jsx,.ts,.tsx
