name: Snyk test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    paths:
      - 'requirements.txt'
      - 'rekono/frontend/package.json'

jobs:
  snyk:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Python dependencies
        shell: bash
        run: |
          apt-get update -y
          apt-get install -y libmagic1 libmagic-dev
          python3 -m pip install -r requirements.txt

      - name: Test Django Project
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-django.sarif
      
      # - name: Upload Django report to GitHub Code Scanning
      #  uses: github/codeql-action/upload-sarif@v1
      #  with:
      #    sarif_file: snyk-django.sarif

      - name: Install Node dependencies
        shell: bash
        run: |
          cd rekono/frontend
          npm install

      - name: Test Vue.JS Project
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=rekono/frontend/package.json --sarif-file-output=snyk-vue.sarif
      
      # - name: Upload Vue.JS report to GitHub Code Scanning
      #  uses: github/codeql-action/upload-sarif@v1
      #  with:
      #    sarif_file: snyk-vue.sarif
