name: Secrets scanning
on:
  workflow_dispatch:
  push:

jobs:
  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install detect-secrets
        run: pip install detect-secrets==1.0.3

      - name: Scan
        id: scan
        shell: bash
        run: |
          detect-secrets scan --baseline .secrets.baseline
          secrets=$(cat .secrets.baseline | jq -c '.results | .[] | .[] | select(.is_secret != false)' | wc -l | sed 's/^ *//g')
          echo "$secrets secrets found"
          echo ::set-output name=secrets:: $secrets

      - name: Fail if findings found
        if: steps.scan.outputs.secrets > 0
        shell: bash
        run: exit 10
          