name: Unit testing
on:
  workflow_dispatch:
  pull_request:

env:
  REQUIRED_COVERAGE: 95

jobs:
  unit-testing:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install and start Redis server
        run: |
          sudo apt update -y
          sudo apt install redis-server -y
          sudo systemctl start redis-server

      - name: Install Nmap to check its installation
        run: sudo apt install nmap -y

      - name: Install Dirsearch to check its installation
        run: |
          git clone https://github.com/maurosoria/dirsearch.git
          ln -s dirsearch/dirsearch.py /usr/local/bin/dirsearch

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd rekono
          coverage run manage.py test
      
      - name: Check coverage
        run: |
          cd rekono
          coverage report -m --skip-covered --fail-under=$REQUIRED_COVERAGE
